"""Paper trading: portfolios, orders, risk_decisions, trades, cash_ledger, positions, snapshots

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-29 11:23:49.885916
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("mode", sa.String(length=10), server_default="live_paper", nullable=False),
        sa.Column("starting_capital", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cash", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('live_paper', 'backtest')", name=op.f("ck_portfolios_mode_valid")
        ),
        sa.CheckConstraint("cash >= 0", name=op.f("ck_portfolios_cash_not_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolios")),
        sa.UniqueConstraint("name", name=op.f("uq_portfolios_name")),
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cash", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("positions_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("total_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_snapshots_portfolio_id_portfolios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_snapshots")),
        sa.UniqueConstraint("portfolio_id", "as_of", name="portfolio_as_of"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("avg_cost", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("cost_basis", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column(
            "realized_pnl", sa.Numeric(precision=20, scale=8), server_default="0", nullable=False
        ),
        sa.Column("stop_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("target_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_entry_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_positions_quantity_not_negative")),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_positions_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_positions_portfolio_id_portfolios"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_positions_signal_id_signals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_index(
        "uq_positions_open",
        "positions",
        ["portfolio_id", "asset_id"],
        unique=True,
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    op.create_table(
        "risk_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=10), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rules_evaluated", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_notional", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("approved_notional", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("portfolio_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('approved', 'reduced', 'rejected')",
            name=op.f("ck_risk_decisions_decision_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_risk_decisions_portfolio_id_portfolios"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_risk_decisions_signal_id_signals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_decisions")),
        sa.UniqueConstraint("signal_id", "portfolio_id", name="signal_portfolio"),
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("reason", sa.String(length=12), server_default="signal", nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("reference_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("slippage_bps", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("fee", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cash_change", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column(
            "realized_pnl", sa.Numeric(precision=20, scale=8), server_default="0", nullable=False
        ),
        sa.Column("price_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("side IN ('BUY', 'SELL')", name=op.f("ck_trades_side_valid")),
        sa.CheckConstraint("fee >= 0", name=op.f("ck_trades_fee_not_negative")),
        sa.CheckConstraint("price > 0", name=op.f("ck_trades_price_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_trades_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_trades_asset_id_assets"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_trades_portfolio_id_portfolios"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_trades_signal_id_signals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
        sa.UniqueConstraint("seq", name=op.f("uq_trades_seq")),
    )
    op.create_index("ix_trades_asset_executed", "trades", ["asset_id", "executed_at"], unique=False)
    op.create_index("ix_trades_portfolio_seq", "trades", ["portfolio_id", "seq"], unique=False)
    op.create_table(
        "cash_ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('deposit', 'trade')", name=op.f("ck_cash_ledger_kind_valid")),
        sa.CheckConstraint("balance_after >= 0", name=op.f("ck_cash_ledger_balance_not_negative")),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_cash_ledger_portfolio_id_portfolios"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
            name=op.f("fk_cash_ledger_trade_id_trades"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_ledger")),
        sa.UniqueConstraint("seq", name=op.f("uq_cash_ledger_seq")),
    )
    op.create_index(
        "ix_cash_ledger_portfolio_seq", "cash_ledger", ["portfolio_id", "seq"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=True),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("reason", sa.String(length=12), server_default="signal", nullable=False),
        sa.Column("notional", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("stop_loss_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("take_profit_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="pending", nullable=False),
        sa.Column("signal_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trade_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('signal', 'stop_loss', 'take_profit')", name=op.f("ck_orders_reason_valid")
        ),
        sa.CheckConstraint("side IN ('BUY', 'SELL')", name=op.f("ck_orders_side_valid")),
        sa.CheckConstraint(
            "status IN ('pending', 'filled', 'expired')", name=op.f("ck_orders_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_orders_asset_id_assets"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["risk_decisions.id"],
            name=op.f("fk_orders_decision_id_risk_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_orders_portfolio_id_portfolios"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_orders_signal_id_signals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index("ix_orders_pending", "orders", ["portfolio_id", "status"], unique=False)
    # ### end Alembic commands ###

    _append_only()


# Money history is never rewritten; a correction is a new opposing row. TRUNCATE stays open (tests).
_TABLES = ("risk_decisions", "trades", "cash_ledger", "portfolio_snapshots")


def _append_only() -> None:
    for table in _TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
        )


def downgrade() -> None:
    for table in _TABLES:
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_orders_pending", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_cash_ledger_portfolio_seq", table_name="cash_ledger")
    op.drop_table("cash_ledger")
    op.drop_index("ix_trades_portfolio_seq", table_name="trades")
    op.drop_index("ix_trades_asset_executed", table_name="trades")
    op.drop_table("trades")
    op.drop_table("risk_decisions")
    op.drop_index(
        "uq_positions_open", table_name="positions", postgresql_where=sa.text("closed_at IS NULL")
    )
    op.drop_table("positions")
    op.drop_table("portfolio_snapshots")
    op.drop_table("portfolios")
    # ### end Alembic commands ###
