"""performance evaluations

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-29 11:46:11.563008
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "performance_evaluations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("horizon", sa.String(length=3), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("start_price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("end_price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("end_price_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("return_pct", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("mfe_pct", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("mae_pct", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("benchmark_symbol", sa.String(length=32), nullable=True),
        sa.Column("benchmark_return_pct", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("excess_return_pct", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("direction_correct", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "horizon IN ('1d', '3d', '7d', '30d')",
            name=op.f("ck_performance_evaluations_horizon_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_performance_evaluations_signal_id_signals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_performance_evaluations")),
        sa.UniqueConstraint("signal_id", "horizon", name="signal_horizon"),
    )
    # ### end Alembic commands ###
    op.execute(
        "CREATE TRIGGER performance_evaluations_append_only BEFORE UPDATE OR DELETE "
        "ON performance_evaluations FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER performance_evaluations_append_only ON performance_evaluations")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("performance_evaluations")
    # ### end Alembic commands ###
